[package]
name = "ocme"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
sailfish = { version = "0.8.3", }
hyper = { version = "1.0.1", features = ["http1", "http2", "server"] }
tungstenite = { version = "0.21.0" }
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros", "net", "sync"] }
oxide-auth = { version = "0.5.4" }
quinn = { version = "0.10.2" }
serde = "1.0.193"

[build-dependencies]
sailfish = "0.8.3"

[[bin]]
name = "ocme-server"
path = "src/bin/server.rs"
test = false

[[bin]]
name = "ocme"
path = "src/bin/management.rs"
test = false

[lib]
name = "ocme-common"
path = "src/common.rs"
test = true
doctest = true
bench = true
doc = true
proc-macro = false
harness = false

[lib]
name = "ocme-macros"
path = "src/macros.rs"
test = false
doctest = true
bench = false
doc = true
proc-macro = true
harness = false

